spring:
  application:
    name: cardiac-diagnosis-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET}

external:
  diagnosis-api-url: ${EXTERNAL_DIAGNOSIS_API_URL:http://localhost:3232}

bookmark:
  kafka:
    topic: bookmark.created

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
