spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    # This is the registry itself - it doesn't need to register with
    # itself or fetch a registry from anyone else.
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
